"""The canonical on-disk layout of a shelf workspace (plan §7.3, SCHEMA.md §2).

This module is pure data: the set of directories to create and the seed files to
write. ``initializer`` consumes it; ``paths`` exposes typed accessors for each path.
"""

from __future__ import annotations

# Marker directory that identifies a workspace root.
DOT_SHELF = ".shelf"

# Human-facing canonical library directories (relative to the workspace root).
LIBRARY_DIRS: tuple[str, ...] = (
    "Inbox",
    "Topics",
    "Sources",
    "Items",
    "Wiki",
    "Digests",
    "Compilations",
    "Review",
    "Review/pending",
    "Review/approved",
    "Review/rejected",
    "Review/stale_claims",
    "Ledgers",
)

# Machine-state directories under ``.shelf/`` (caches, not canonical artifacts).
SHELF_DIRS: tuple[str, ...] = (
    DOT_SHELF,
    f"{DOT_SHELF}/index",
    f"{DOT_SHELF}/snapshots",
    f"{DOT_SHELF}/normalized",
    f"{DOT_SHELF}/cache",
)

# Every directory `shelf init` creates.
ALL_DIRS: tuple[str, ...] = LIBRARY_DIRS + SHELF_DIRS

# Append-only ledgers seeded empty (plan §7.3).
LEDGER_FILES: tuple[str, ...] = (
    "Ledgers/source_ledger.jsonl",
    "Ledgers/claim_ledger.jsonl",
)

DASHBOARD_FILE = "Dashboard.md"
REVIEW_QUEUE_FILE = "Inbox/review_queue.md"


def dashboard_markdown(name: str, root: str, created_at: str) -> str:
    """Initial ``Dashboard.md`` content for a fresh workspace."""
    return (
        f"# {name}\n\n"
        f"A local-first **shelf** research library.\n\n"
        f"- Root: `{root}`\n"
        f"- Created: {created_at}\n\n"
        "## Getting started\n\n"
        "- `shelf status` — show library status (sources / inbox / review)\n"
        "- `shelf chat` — open the research REPL (coming in Phase 5)\n\n"
        "This dashboard is regenerated by `shelf status`/rebuild as the library grows.\n"
    )


def review_queue_markdown() -> str:
    """Initial ``Inbox/review_queue.md`` placeholder."""
    return (
        "# Review Queue\n\n"
        "No pending review items yet.\n\n"
        "Items, source candidates, stale claims, and wiki patches awaiting your "
        "approval will appear here (mirrored from `Review/pending/`).\n"
    )
